import DataObjects.DerbyTableWrapper;

import javax.swing.*;

public class Main {
    private static DerbyTableWrapper wrapper;

    public static void main(String[] args){
        System.out.println("Hello there Quizmo");

        DerbyTableWrapper wrapper = new DerbyTableWrapper();
        wrapper.createProductsTable();
        wrapper.createSalesTable();

        // NOTE: generator generates data for 2018 and 2019.
        PharmacyDataGenerator theGenerator = new PharmacyDataGenerator();
        // second parameter = number of records to generate. If things are slow, make it smaller.
        theGenerator.generateData(wrapper, 10000);

        // used to check the contents generated by theGenerator by outputting to CSV
        //CSVReport report = new CSVReport(wrapper.getSales());
        //report.writeToFile("SarahTest");

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new InterfaceController(wrapper);
            }
        });

    }
}
