package DataObjects;

/**
 * represents an entry in the products table
 */
public class Product {

    private int productID; // autogenerated
    private String productName;
    private Float pricePerUnit;
    private String productCategory;

    /**
     * for retrieving data
     */
    public Product(int productID, String productName, Float pricePerUnit, String productCategory){
        this.productID = productID;
        this.productName = productName;
        this.pricePerUnit = pricePerUnit;
        this.productCategory = productCategory;
    }

    /**
     * for ADDING data (productID is autogenerated)
     */
    public Product(String productName, Float pricePerUnit, String productCategory){
        this.productName = productName;
        this.pricePerUnit = pricePerUnit;
        this.productCategory = productCategory;
    }

    /**
     * the product category that is chosen
     * when we don't want a product category filter.
     * @return
     */
    public static String getNoProductCat(){
        return "No Product Filter";
    }

    public int getProductID() {
        return productID;
    }

    public String getProductName() {
        return productName;
    }

    public Float getPricePerUnit() {
        return pricePerUnit;
    }

    public String getProductCategory() {
        return productCategory;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public void setPricePerUnit(Float pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }

    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    @Override
    public String toString(){
        // for appropriate string display in drop-down
        return toProductFilterString();
        /*
        String toReturn = "Product( ";
        toReturn += "\nproductID = "+ productID;
        toReturn += "\nproductName = "+productName;
        toReturn += "\npricePerUnit = $"+pricePerUnit;
        toReturn += "\nproductCategory = "+productCategory;
        toReturn += ")";
        return toReturn;*/
    }

    public String toProductFilterString(){
        return productID +  " - " + productName;
    }

}
