package DataObjects;

/**
 * represents an entry in the products table
 */
public class Product {

    private int productID; // autogenerated
    private String productName;
    private Float pricePerUnit; // TODO: regex should check this is to two decimal places
    private String productCategory;

    /**
     * for retrieving data
     */
    public Product(int productID, String productName, Float pricePerUnit, String productCategory){
        this.productID = productID;
        this.productName = productName;
        this.pricePerUnit = pricePerUnit;
        this.productCategory = productCategory;
    }

    /**
     * for ADDING data (productID is autogenerated)
     */
    public Product(String productName, Float pricePerUnit, String productCategory){
        this.productName = productName;
        this.pricePerUnit = pricePerUnit;
        this.productCategory = productCategory;
    }

    public int getProductID() {
        return productID;
    }

    public String getProductName() {
        return productName;
    }

    public Float getPricePerUnit() {
        return pricePerUnit;
    }

    public String getProductCategory() {
        return productCategory;
    }

}
