package DataObjects;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 * represents a sale entry in the product sales table
 */
public class Sale {

    private int entryID; // autogenerated
    private String saleID;
    private int productID;
    private int numberSold;
    private float amountPaid;
    private String saleStatus;
    private Date dateOfSale;

    private String productCategory; // for searches with product category. WILL NOT ALWAYS EXIST.


    /**
     * for retrieving data
     */
    public Sale(int entryID, String saleID, int productID, String dateOfSaleString,
                int numberSold, float amountPaid, String saleStatus){
        checkDateRegex(dateOfSaleString);
        this.entryID = entryID;
        this.saleID = saleID;
        this.productID = productID;
        this.dateOfSale = convertDateStringToDate(dateOfSaleString);
        this.numberSold = numberSold;
        this.amountPaid = amountPaid;
        this.saleStatus = saleStatus;
    }

    /**
     * for ADDING data (entryID is autogenerated)
     */
    public Sale(String saleID, int productID, String dateOfSaleString,
                int numberSold, float amountPaid, String saleStatus){
        checkDateRegex(dateOfSaleString);
        this.saleID = saleID;
        this.productID = productID;
        this.dateOfSale = convertDateStringToDate(dateOfSaleString);
        this.numberSold = numberSold;
        this.amountPaid = amountPaid;
        this.saleStatus = saleStatus;
    }

    public Sale(int entryID, String saleID, int productID, Date dateOfSale,
                int numberSold, float amountPaid, String saleStatus){
        this.entryID = entryID;
        this.saleID = saleID;
        this.productID = productID;
        this.dateOfSale = dateOfSale;
        this.numberSold = numberSold;
        this.amountPaid = amountPaid;
        this.saleStatus = saleStatus;
    }

    /**
     * if date string does not match the required regex of DD-MM-YYYY
     * throw an IllegalArgumentException
     */
    private void checkDateRegex(String date){
        if (!date.matches("\\d{2}-\\d{2}-\\d{4}")){
            throw new IllegalArgumentException("SALE object was created with malformed date\n" +
                    "Expected Structure = 'DD-MM-YYYY' (all digits)\n" +
                    "Received date string = '"+date+"'");
        }
    }

    public int getEntryID() {
        return entryID;
    }

    public String getSaleID() {
        return saleID;
    }

    public int getProductID() {
        return productID;
    }

    public Date getDateOfSale(){ return dateOfSale; }

    private Date convertDateStringToDate(String dateString){
        // DD-MM-YYYY
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        try {
            java.util.Date date = format.parse(dateString);
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        } catch (ParseException e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
            System.out.println("failed to convert date string to sql date\n datestring= "+dateOfSale);
            return null;
        }
    }

    public int getNumberSold() {
        return numberSold;
    }

    public float getAmountPaid() {
        return amountPaid;
    }

    public String getSaleStatus() {
        return saleStatus;
    }

    public void setProductCategory(String category){
        this.productCategory = category;
    }

    public String getProductCategory(){ return this.productCategory; }

    public void setEntryID(int entryID) {
        this.entryID = entryID;
    }

    public void setSaleID(String saleID) {
        this.saleID = saleID;
    }

    public void setProductID(int productID) {
        this.productID = productID;
    }

    public void setNumberSold(int numberSold) {
        this.numberSold = numberSold;
    }

    public void setAmountPaid(float amountPaid) {
        this.amountPaid = amountPaid;
    }

    public void setSaleStatus(String saleStatus) {
        this.saleStatus = saleStatus;
    }

    public void setDateOfSale(Date dateOfSale) {
        this.dateOfSale = dateOfSale;
    }

    public void setDateOfSale(String dateOfSaleString){
        checkDateRegex(dateOfSaleString);
        this.dateOfSale = convertDateStringToDate(dateOfSaleString);
    }

    @Override
    public String toString(){
        String toReturn = "Sale (";
        toReturn += "\nentryID= "+entryID;
        toReturn += "\nsaleID= "+saleID;
        toReturn += "\nproductID= "+productID;
        toReturn +="\ndateOfDale= "+dateOfSale;
        toReturn +="\nnumberSold= "+numberSold;
        toReturn += "\namountPaid=" +amountPaid;
        toReturn += "\nsaleStatus= "+saleStatus;
        toReturn += ")";
        return toReturn;
    }
}
